GET http://localhost:3000/users/

###

GET http://localhost:3000/users/1

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "rafa@gmail.com",
    "name": "Rafa"
}

###

DELETE http://localhost:3000/users/6

###

PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "name": "Rafaello"
}